SELECT 
    id
FROM
    cognome.articles
WHERE
	title not like concat("%","Nonrandom connectivity of the epileptic dentate gyrus predicts a major","%")
AND	title not like concat("%","Role of mossy fiber sprouting and mossy cell loss in hyperexcitability: a network model of the dentate gyrus incorporating cell types and axonal topography","%")
AND	title not like concat("%","Velocity-Controlled Oscillators for Hippocampal Navigation on Spiking Neuromorphic Hardwar","%")
AND	title not like concat("%","Conjunctive Representations in Learning and Memory: Principles of Cortical and Hippocampal Functio","%")
AND	title not like concat("%","Computational influence of adult neurogenesis on memory encoding","%")
AND	title not like concat("%","Shunting inhibition improves robustness of gamma oscillations in hippocampal interneuron networks by homogenizing firing rate","%")
AND	title not like concat("%","Intrinsic and network rhythmogenesis in a reduced Traub model for CA3 neurons","%")
AND	title not like concat("%","NMDA-dependent modulation of CA1 local circuit inhibition","%")
AND	title not like concat("%","Slow periodic activity in the longitudinal hippocampal slice can self‐propagate non‐synaptically by a mechanism consistent with ephaptic coupling","%")
AND	title not like concat("%","Hippocampal mechanisms for the context-dependent retrieval of episodes","%")
AND	title not like concat("%","Multimodal determinants of phase-locked dynamics across deep-superficial hippocampal sublayers during theta oscillations","%")
AND	title not like concat("%","Large time step discrete-time modeling of sharp wave activity in hippocampal area CA3","%")
AND	title not like concat("%","Circuit mechanisms of hippocampal reactivation during slee","%")
AND	title not like concat("%","Vasoactive Intestinal Polypeptide-Expressing Interneurons in the Hippocampus Support Goal-Oriented Spatial Learnin","%")
AND	title not like concat("%","Low-intensity electrical stimulation affects network dynamics by modulating population rate and spike timing","%")
AND	title not like concat("%","A mechanism for generation of long-range synchronous fast oscillations in the corte","%")
AND	title not like concat("%","Mechanisms of sharp wave initiation and ripple generatio","%")
AND	title not like concat("%","Analysis of gamma rhythms in the rat hippocampus in vitro and in vivoSymmetric spike timing-dependent plasticity at CA3-CA3 synapses optimizes storage and recall in autoassociative network","%")
AND	title not like concat("%","Epilepsy in small-world network","%")
AND	title not like concat("%","Emergent Dynamics of Fast Ripples in the Epileptic Hippocampus","%")
AND	title not like concat("%","Parvalbumin-positive basket cells differentiate among hippocampal pyramidal cells","%")
AND	title not like concat("%","High-Degree Neurons Feed Cortical Computations","%")
AND	title not like concat("%","Topological determinants of epileptogenesis in large-scale structural and functional models of the dentate gyrus derived from experimental data","%")
AND	title not like concat("%","Cellular mechanism of neuronal synchronization in epilepsy","%")
AND	title not like concat("%","Decoupling through synchrony in neuronal circuits with propagation delays","%")
AND	title not like concat("%","Rapid signaling at inhibitory synapses in a dentate gyrus interneuron networ","%")
AND	title not like concat("%","Chaotic dynamics as a mechanism of rapid transition of hippocampal local field activity between theta and non-theta states","%")
AND	title not like concat("%","Computer Modeling of Alzheimer's Disease-Simulations of Synaptic Plasticity and Memory in the CA3-CA1 Hippocampal Formation Microcircuit","%")
AND	title not like concat("%","Hippocampal-Cortical Memory Trace Transfer and Reactivation Through Cell-Specific Stimulus and Spontaneous Background Noise","%")
AND	title not like concat("%","Modeling of Brain-Like Concept Coding with Adulthood Neurogenesis in the Dentate Gyrus","%")
AND	title not like concat("%","Network Activity Due to Topographic Organization of Schaffer Collaterals in a Large-Scale Model of Rat CA1","%")
AND	title not like concat("%","A kernel-based method to calculate local field potentials from networks of spiking neurons","%")
AND	title not like concat("%","Admittance Method for Estimating Local Field Potentials Generated in a Multi-Scale Neuron Model of the Hippocampus","%")
AND	title not like concat("%","Volume-Conducted Origin of the Field Potential at the Lateral Habenula","%")
AND	title not like concat("%","An uncertainty principle for neural coding: Conjugate representations of position and velocity are mapped onto firing rates and co-firing rates of neural spike trains","%")
AND	title not like concat("%","Quantitative properties of a feedback circuit predict frequency-dependent pattern separation","%")
AND	title not like concat("%","Spatiotemporally random and diverse grid cell spike patterns contribute to the transformation of grid cell to place cell in a neural network model","%")
AND	title not like concat("%","Phase relations of theta oscillations in a computer model of the hippocampal CA1 field: Key role of Schaffer collaterals","%")
AND	title not like concat("%","A diversity of interneurons and Hebbian plasticity facilitate rapid compressible learning in the hippocampu","%")
AND	title not like concat("%","Disparate forms of heterogeneities and interactions among them drive channel decorrelation in the dentate gyrus: Degeneracy and dominance","%")
AND	title not like concat("%","A model of cholinergic suppression of hippocampal ripples through disruption of balanced excitation/inhibition","%")
AND	title not like concat("%","Impairment of Sharp-Wave Ripples in a Murine Model of Dravet Syndrome","%")
AND	title not like concat("%","Modulating grid cell scale and intrinsic frequencies via slow high-threshold conductances: A simplified model","%")
AND	title not like concat("%","Axonal Anatomy Optimizes Spatial Encoding in the Rat Entorhinal-Dentate System: A Computational Study","%")
AND	title not like concat("%","Hippocampal Neurogenesis Reduces the Dimensionality of Sparsely Coded Representations to Enhance Memory Encoding","%")
AND	title not like concat("%","A Proposed Mechanism for Spontaneous Transitions between Interictal and Ictal Activit","%")
AND	title not like concat("%","A geometric attractor mechanism for self-organization of entorhinal grid module","%")
AND	title not like concat("%","Effect of mutant NMDA receptors on the oscillations in a model of hippocampus","%")
AND	title not like concat("%","Dendritic NMDA receptors in parvalbumin neurons enable strong and stable neuronal assemblies","%")
AND	title not like concat("%","Pattern separation, completion, and categorisation in the hippocampus and neocortex","%")
AND	title not like concat("%","Environmental deformations dynamically shift the grid cell spatial metric","%")
AND	title not like concat("%","Dynamically reconfigurable silicon array of spiking neurons with conductance-based synapses","%")
AND	title not like concat("%","A sequence predicting CA3 is a flexible associator that learns and uses context to solve hippocampal‐like tasks","%")
AND	title not like concat("%","Synchronization and oscillatory dynamics in heterogeneous, mutually inhibited neurons","%")
AND	title not like concat("%","Memory replay in balanced recurrent networks","%")
AND	title not like concat("%","Sequential neuromodulation of Hebbian plasticity offers mechanism for effective reward-based navigation","%")
AND	title not like concat("%","Interpyramid spike transmission stabilizes the sparseness of recurrent network activit","%")
AND	title not like concat("%","Improving Spiking Dynamical Networks: Accurate Delays, Higher-Order Synapses, and Time Cells","%")
AND	title not like concat("%","A model of gamma-frequency network oscillations induced in the rat CA3 region by carbachol in vitro","%")
AND	title not like concat("%","GABAergic modulation of hippocampal population activity: sequence learning, place field development, and the phase precession effect","%")
AND	title not like concat("%","Increased dentate gyrus excitability in neuroligin-2-deficient mice in viv","%")
AND	title not like concat("%","High-frequency population oscillations are predicted to occur in hippocampal pyramidal neuronal networks interconnected by axoaxonal gap junctions","%")
AND	title not like concat("%","Cellular correlate of assembly formation in oscillating hippocampal networks in vitro","%")
AND	title not like concat("%","Pattern separation in the dentate gyrus: a role for the CA3 backprojectioOn the mechanism of the gamma -- beta frequency shift in neuronal oscillations induced in rat hippocampal slices by tetanic stimulation","%")
AND	title not like concat("%","Mnemonic functions for nonlinear dendritic integration in hippocampal pyramidal circuit","%")
AND	title not like concat("%","Slow and fast inhibition and an H-current interact to create a theta rhythm in a model of CA1 interneuron network","%")
AND	title not like concat("%","The spiking component of oscillatory extracellular potentials in the rat hippocampus","%")
AND	title not like concat("%","A model of a CA3 hippocampal pyramidal neuron incorporating voltage-clamp data on intrinsic conductances","%")
AND	title not like concat("%","Feasibility and resolution limits of opto-magnetic imaging of neural network activity in brain slices using color centers in diamond","%")
AND	title not like concat("%","Modeling sharp wave-ripple complexes through a CA3-CA1 network model with chemical synapses","%")
AND	title not like concat("%","Pacemaker neurons for the theta rhythm and their synchronization in the septohippocampal reciprocal loop","%")
AND	title not like concat("%","Synchronization of strongly coupled excitatory neurons: relating network behavior to biophysic","%")
AND	title not like concat("%","Hippocampal gamma-frequency oscillations: from interneurones to pyramidal cells, and back","%")
AND	title not like concat("%","Modeling fast and slow gamma oscillations with interneurons of different subtype","%")
AND	title not like concat("%","New roles for the gamma rhythm: population tuning and preprocessing for the Beta rhyth","%")
AND	title not like concat("%","Networks of interneurons with fast and slow gamma-aminobutyric acid type A (GABAA) kinetics provide substrate for mixed gamma-theta rhythm","%")
AND	title not like concat("%","Spatiotemporal patterns of gamma frequency oscillations tetanically induced in the rat hippocampal slice","%")
AND	title not like concat("%","Impaired hippocampal rhythmogenesis in a mouse model of mesial temporal lobe epilepsy","%")
AND	title not like concat("%","Astrocyte- neuron interaction as a mechanism responsible for generation of neural synchrony: a study based on modeling and experiments","%")
AND	title not like concat("%","Recurrent Spiking Networks Solve Planning Tasks","%")
AND	title not like concat("%","Transformation of a Spatial Map across the Hippocampal-Lateral Septal Circuit","%")
AND	title not like concat("%","Nonlinear modeling of neural population dynamics for hippocampal prosthese","%")
AND	title not like concat("%","Can Neural Activity Propagate by Endogenous Electrical Field","%")
AND	title not like concat("%","Gamma oscillation by synaptic inhibition in a hippocampal interneuronal network model","%")
AND	title not like concat("%","Path integration and cognitive mapping in a continuous attractor neural network model","%")
AND	title not like concat("%","Hippocampal theta rhythm and its coupling with gamma oscillations require fast inhibition onto parvalbumin-positive interneurons","%")
AND	title not like concat("%","Feedback Inhibition Enables Theta-Nested Gamma Oscillations and Grid Firing FieldInterneuronal mechanisms of hippocampal theta oscillations in a full-scale model of the rodent CA1 circui","%")
AND	title not like concat("%","A hybrid oscillatory interference/continuous attractor network model of grid cell firin","%")
AND	title not like concat("%","FPGA implementation of hippocampal spiking network and its real-time simulation on dynamical neuromodulation of oscillation","%")
AND	title not like concat("%","Role of mossy fiber sprouting and mossy cell loss in hyperexcitability: a network model of the dentate gyrus incorporating cell types and axonal topograph","%")
AND	title not like concat("%","Encoding and retrieval in a model of the hippocampal CA1 microcircui","%")
AND	title not like concat("%","Population dynamics and theta rhythm phase precession of hippocampal place cell firing: a spiking neuron mode","%")
AND	title not like concat("%","A Model for Grid Firing and Theta-Nested Gamma Oscillations in Layer 2 of the Medial Entorhinal Cortex","%")
AND	title not like concat("%","Velocity-Controlled Oscillators for Hippocampal Navigation on Spiking Neuromorphic Hardware","%")
AND	title not like concat("%","The Generation of Time in the Hippocampal Memory System","%")
AND	title not like concat("%","Fast synaptic inhibition promotes synchronized gamma oscillations in hippocampal interneuron networks","%")
AND	title not like concat("%","Regulation of gamma-frequency oscillation by feedforward inhibition: A computational modeling study","%")
AND	title not like concat("%","A neural microcircuit model for a scalable scale-invariant representation of tim","%")
AND	title not like concat("%","Fast and flexible sequence induction in spiking neural networks via rapid excitability change","%")
AND	title not like concat("%","Accurate path integration in continuous attractor network models of grid cell","%")
AND	title not like concat("%","Synaptic mechanisms of pattern completion in the hippocampal CA3 network","%")
AND	title not like concat("%","Environmental boundaries as an error correction mechanism for grid cell","%")
AND	title not like concat("%","Phase precession and variable spatial scaling in a periodic attractor map model of medial entorhinal grid cells with realistic after-spike dynamics","%")
AND	title not like concat("%","A novel pyramidal cell type promotes sharp-wave synchronization in the hippocampus","%")
AND	title not like concat("%","Hippocampal Ripple Oscillations and Inhibition-First Network Models: Frequency Dynamics and Response to GABA Modulator","%")
AND	title not like concat("%","From grid cells to place cells with realistic field size","%")
AND	title not like concat("%","Dendrites of dentate gyrus granule cells contribute to pattern separation by controlling sparsit","%")
AND	title not like concat("%","Ketamine disrupts","%")
AND	title not like concat("%","A model of high-frequency ripples in the hippocampus based on synaptic coupling plus axon-axon gap junctions between pyramidal neuron","%")
AND	title not like concat("%","Coupled noisy spiking neurons as velocity-controlled oscillators in a model of grid cell spatial firing","%")
AND	title not like concat("%","Recurrent network model for learning goal-directed sequences through reverse repla","%")
AND	title not like concat("%","A Unified Dynamic Model for Learning, Replay, and Sharp-Wave/Ripples","%")
AND	title not like concat("%","A model of episodic memory: mental time travel along encoded trajectories using grid cells","%")